package com.juqueen.flatshare;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PacketProto.proto

public final class PacketProto {
  private PacketProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Packet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Packet.Header header = 7;</code>
     */
    java.util.List<Packet.Header>
        getHeaderList();
    /**
     * <code>repeated .Packet.Header header = 7;</code>
     */
    Packet.Header getHeader(int index);
    /**
     * <code>repeated .Packet.Header header = 7;</code>
     */
    int getHeaderCount();
    /**
     * <code>repeated .Packet.Header header = 7;</code>
     */
    java.util.List<? extends Packet.HeaderOrBuilder>
        getHeaderOrBuilderList();
    /**
     * <code>repeated .Packet.Header header = 7;</code>
     */
    Packet.HeaderOrBuilder getHeaderOrBuilder(
            int index);

    /**
     * <code>repeated .Packet.Data data = 8;</code>
     */
    java.util.List<Packet.Data>
        getDataList();
    /**
     * <code>repeated .Packet.Data data = 8;</code>
     */
    Packet.Data getData(int index);
    /**
     * <code>repeated .Packet.Data data = 8;</code>
     */
    int getDataCount();
    /**
     * <code>repeated .Packet.Data data = 8;</code>
     */
    java.util.List<? extends Packet.DataOrBuilder>
        getDataOrBuilderList();
    /**
     * <code>repeated .Packet.Data data = 8;</code>
     */
    Packet.DataOrBuilder getDataOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code Packet}
   */
  public static final class Packet extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Packet)
      PacketOrBuilder {
    // Use Packet.newBuilder() to construct.
    private Packet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Packet(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Packet defaultInstance;
    public static Packet getDefaultInstance() {
      return defaultInstance;
    }

    public Packet getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Packet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                header_ = new java.util.ArrayList<Header>();
                mutable_bitField0_ |= 0x00000001;
              }
              header_.add(input.readMessage(Header.PARSER, extensionRegistry));
              break;
            }
            case 66: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                data_ = new java.util.ArrayList<Data>();
                mutable_bitField0_ |= 0x00000002;
              }
              data_.add(input.readMessage(Data.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          header_ = java.util.Collections.unmodifiableList(header_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PacketProto.internal_static_Packet_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PacketProto.internal_static_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Packet.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Packet> PARSER =
        new com.google.protobuf.AbstractParser<Packet>() {
      public Packet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Packet(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Packet> getParserForType() {
      return PARSER;
    }

    public interface HeaderOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Packet.Header)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int32 code = 1;</code>
       */
      boolean hasCode();
      /**
       * <code>required int32 code = 1;</code>
       */
      int getCode();

      /**
       * <code>optional string intent = 2;</code>
       */
      boolean hasIntent();
      /**
       * <code>optional string intent = 2;</code>
       */
      String getIntent();
      /**
       * <code>optional string intent = 2;</code>
       */
      com.google.protobuf.ByteString
          getIntentBytes();

      /**
       * <code>optional string data = 3;</code>
       */
      boolean hasData();
      /**
       * <code>optional string data = 3;</code>
       */
      String getData();
      /**
       * <code>optional string data = 3;</code>
       */
      com.google.protobuf.ByteString
          getDataBytes();

      /**
       * <code>optional int32 data_length = 4;</code>
       */
      boolean hasDataLength();
      /**
       * <code>optional int32 data_length = 4;</code>
       */
      int getDataLength();
    }
    /**
     * Protobuf type {@code Packet.Header}
     */
    public static final class Header extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:Packet.Header)
        HeaderOrBuilder {
      // Use Header.newBuilder() to construct.
      private Header(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Header(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Header defaultInstance;
      public static Header getDefaultInstance() {
        return defaultInstance;
      }

      public Header getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Header(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                code_ = input.readInt32();
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                intent_ = bs;
                break;
              }
              case 26: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000004;
                data_ = bs;
                break;
              }
              case 32: {
                bitField0_ |= 0x00000008;
                dataLength_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PacketProto.internal_static_Packet_Header_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PacketProto.internal_static_Packet_Header_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Header.class, Builder.class);
      }

      public static com.google.protobuf.Parser<Header> PARSER =
          new com.google.protobuf.AbstractParser<Header>() {
        public Header parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Header(input, extensionRegistry);
        }
      };

      @Override
      public com.google.protobuf.Parser<Header> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int CODE_FIELD_NUMBER = 1;
      private int code_;
      /**
       * <code>required int32 code = 1;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 code = 1;</code>
       */
      public int getCode() {
        return code_;
      }

      public static final int INTENT_FIELD_NUMBER = 2;
      private Object intent_;
      /**
       * <code>optional string intent = 2;</code>
       */
      public boolean hasIntent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string intent = 2;</code>
       */
      public String getIntent() {
        Object ref = intent_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            intent_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string intent = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIntentBytes() {
        Object ref = intent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          intent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int DATA_FIELD_NUMBER = 3;
      private Object data_;
      /**
       * <code>optional string data = 3;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string data = 3;</code>
       */
      public String getData() {
        Object ref = data_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            data_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string data = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int DATA_LENGTH_FIELD_NUMBER = 4;
      private int dataLength_;
      /**
       * <code>optional int32 data_length = 4;</code>
       */
      public boolean hasDataLength() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 data_length = 4;</code>
       */
      public int getDataLength() {
        return dataLength_;
      }

      private void initFields() {
        code_ = 0;
        intent_ = "";
        data_ = "";
        dataLength_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasCode()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, code_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getIntentBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getDataBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeInt32(4, dataLength_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, code_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getIntentBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getDataBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, dataLength_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      protected Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static Header parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Header parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Header parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Header parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Header parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Header parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static Header parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static Header parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static Header parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Header parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(Header prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Packet.Header}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Packet.Header)
          HeaderOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return PacketProto.internal_static_Packet_Header_descriptor;
        }

        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return PacketProto.internal_static_Packet_Header_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Header.class, Builder.class);
        }

        // Construct using PacketProto.Packet.Header.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          code_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          intent_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          data_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          dataLength_ = 0;
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return PacketProto.internal_static_Packet_Header_descriptor;
        }

        public Header getDefaultInstanceForType() {
          return Header.getDefaultInstance();
        }

        public Header build() {
          Header result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public Header buildPartial() {
          Header result = new Header(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.code_ = code_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.intent_ = intent_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.data_ = data_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.dataLength_ = dataLength_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Header) {
            return mergeFrom((Header)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Header other) {
          if (other == Header.getDefaultInstance()) return this;
          if (other.hasCode()) {
            setCode(other.getCode());
          }
          if (other.hasIntent()) {
            bitField0_ |= 0x00000002;
            intent_ = other.intent_;
            onChanged();
          }
          if (other.hasData()) {
            bitField0_ |= 0x00000004;
            data_ = other.data_;
            onChanged();
          }
          if (other.hasDataLength()) {
            setDataLength(other.getDataLength());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasCode()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Header parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Header) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int code_ ;
        /**
         * <code>required int32 code = 1;</code>
         */
        public boolean hasCode() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 code = 1;</code>
         */
        public int getCode() {
          return code_;
        }
        /**
         * <code>required int32 code = 1;</code>
         */
        public Builder setCode(int value) {
          bitField0_ |= 0x00000001;
          code_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 code = 1;</code>
         */
        public Builder clearCode() {
          bitField0_ = (bitField0_ & ~0x00000001);
          code_ = 0;
          onChanged();
          return this;
        }

        private Object intent_ = "";
        /**
         * <code>optional string intent = 2;</code>
         */
        public boolean hasIntent() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string intent = 2;</code>
         */
        public String getIntent() {
          Object ref = intent_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              intent_ = s;
            }
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>optional string intent = 2;</code>
         */
        public com.google.protobuf.ByteString
            getIntentBytes() {
          Object ref = intent_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            intent_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string intent = 2;</code>
         */
        public Builder setIntent(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          intent_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string intent = 2;</code>
         */
        public Builder clearIntent() {
          bitField0_ = (bitField0_ & ~0x00000002);
          intent_ = getDefaultInstance().getIntent();
          onChanged();
          return this;
        }
        /**
         * <code>optional string intent = 2;</code>
         */
        public Builder setIntentBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          intent_ = value;
          onChanged();
          return this;
        }

        private Object data_ = "";
        /**
         * <code>optional string data = 3;</code>
         */
        public boolean hasData() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional string data = 3;</code>
         */
        public String getData() {
          Object ref = data_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              data_ = s;
            }
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>optional string data = 3;</code>
         */
        public com.google.protobuf.ByteString
            getDataBytes() {
          Object ref = data_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            data_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string data = 3;</code>
         */
        public Builder setData(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          data_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string data = 3;</code>
         */
        public Builder clearData() {
          bitField0_ = (bitField0_ & ~0x00000004);
          data_ = getDefaultInstance().getData();
          onChanged();
          return this;
        }
        /**
         * <code>optional string data = 3;</code>
         */
        public Builder setDataBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          data_ = value;
          onChanged();
          return this;
        }

        private int dataLength_ ;
        /**
         * <code>optional int32 data_length = 4;</code>
         */
        public boolean hasDataLength() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional int32 data_length = 4;</code>
         */
        public int getDataLength() {
          return dataLength_;
        }
        /**
         * <code>optional int32 data_length = 4;</code>
         */
        public Builder setDataLength(int value) {
          bitField0_ |= 0x00000008;
          dataLength_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 data_length = 4;</code>
         */
        public Builder clearDataLength() {
          bitField0_ = (bitField0_ & ~0x00000008);
          dataLength_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Packet.Header)
      }

      static {
        defaultInstance = new Header(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Packet.Header)
    }

    public interface DataOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Packet.Data)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional int32 joinee_id = 5;</code>
       */
      boolean hasJoineeId();
      /**
       * <code>optional int32 joinee_id = 5;</code>
       */
      int getJoineeId();

      /**
       * <code>optional int32 unique_pckt_id = 6;</code>
       */
      boolean hasUniquePcktId();
      /**
       * <code>optional int32 unique_pckt_id = 6;</code>
       */
      int getUniquePcktId();
    }
    /**
     * Protobuf type {@code Packet.Data}
     */
    public static final class Data extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:Packet.Data)
        DataOrBuilder {
      // Use Data.newBuilder() to construct.
      private Data(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Data(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Data defaultInstance;
      public static Data getDefaultInstance() {
        return defaultInstance;
      }

      public Data getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Data(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 40: {
                bitField0_ |= 0x00000001;
                joineeId_ = input.readInt32();
                break;
              }
              case 48: {
                bitField0_ |= 0x00000002;
                uniquePcktId_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PacketProto.internal_static_Packet_Data_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PacketProto.internal_static_Packet_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Data.class, Builder.class);
      }

      public static com.google.protobuf.Parser<Data> PARSER =
          new com.google.protobuf.AbstractParser<Data>() {
        public Data parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Data(input, extensionRegistry);
        }
      };

      @Override
      public com.google.protobuf.Parser<Data> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int JOINEE_ID_FIELD_NUMBER = 5;
      private int joineeId_;
      /**
       * <code>optional int32 joinee_id = 5;</code>
       */
      public boolean hasJoineeId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 joinee_id = 5;</code>
       */
      public int getJoineeId() {
        return joineeId_;
      }

      public static final int UNIQUE_PCKT_ID_FIELD_NUMBER = 6;
      private int uniquePcktId_;
      /**
       * <code>optional int32 unique_pckt_id = 6;</code>
       */
      public boolean hasUniquePcktId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 unique_pckt_id = 6;</code>
       */
      public int getUniquePcktId() {
        return uniquePcktId_;
      }

      private void initFields() {
        joineeId_ = 0;
        uniquePcktId_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(5, joineeId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(6, uniquePcktId_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(5, joineeId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(6, uniquePcktId_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      protected Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static Data parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Data parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Data parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Data parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Data parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Data parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static Data parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static Data parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static Data parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Data parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(Data prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Packet.Data}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Packet.Data)
          DataOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return PacketProto.internal_static_Packet_Data_descriptor;
        }

        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return PacketProto.internal_static_Packet_Data_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Data.class, Builder.class);
        }

        // Construct using PacketProto.Packet.Data.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          joineeId_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          uniquePcktId_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return PacketProto.internal_static_Packet_Data_descriptor;
        }

        public Data getDefaultInstanceForType() {
          return Data.getDefaultInstance();
        }

        public Data build() {
          Data result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public Data buildPartial() {
          Data result = new Data(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.joineeId_ = joineeId_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.uniquePcktId_ = uniquePcktId_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Data) {
            return mergeFrom((Data)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Data other) {
          if (other == Data.getDefaultInstance()) return this;
          if (other.hasJoineeId()) {
            setJoineeId(other.getJoineeId());
          }
          if (other.hasUniquePcktId()) {
            setUniquePcktId(other.getUniquePcktId());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Data parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Data) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int joineeId_ ;
        /**
         * <code>optional int32 joinee_id = 5;</code>
         */
        public boolean hasJoineeId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional int32 joinee_id = 5;</code>
         */
        public int getJoineeId() {
          return joineeId_;
        }
        /**
         * <code>optional int32 joinee_id = 5;</code>
         */
        public Builder setJoineeId(int value) {
          bitField0_ |= 0x00000001;
          joineeId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 joinee_id = 5;</code>
         */
        public Builder clearJoineeId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          joineeId_ = 0;
          onChanged();
          return this;
        }

        private int uniquePcktId_ ;
        /**
         * <code>optional int32 unique_pckt_id = 6;</code>
         */
        public boolean hasUniquePcktId() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional int32 unique_pckt_id = 6;</code>
         */
        public int getUniquePcktId() {
          return uniquePcktId_;
        }
        /**
         * <code>optional int32 unique_pckt_id = 6;</code>
         */
        public Builder setUniquePcktId(int value) {
          bitField0_ |= 0x00000002;
          uniquePcktId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 unique_pckt_id = 6;</code>
         */
        public Builder clearUniquePcktId() {
          bitField0_ = (bitField0_ & ~0x00000002);
          uniquePcktId_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Packet.Data)
      }

      static {
        defaultInstance = new Data(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Packet.Data)
    }

    public static final int HEADER_FIELD_NUMBER = 7;
    private java.util.List<Header> header_;
    /**
     * <code>repeated .Packet.Header header = 7;</code>
     */
    public java.util.List<Header> getHeaderList() {
      return header_;
    }
    /**
     * <code>repeated .Packet.Header header = 7;</code>
     */
    public java.util.List<? extends HeaderOrBuilder>
        getHeaderOrBuilderList() {
      return header_;
    }
    /**
     * <code>repeated .Packet.Header header = 7;</code>
     */
    public int getHeaderCount() {
      return header_.size();
    }
    /**
     * <code>repeated .Packet.Header header = 7;</code>
     */
    public Header getHeader(int index) {
      return header_.get(index);
    }
    /**
     * <code>repeated .Packet.Header header = 7;</code>
     */
    public HeaderOrBuilder getHeaderOrBuilder(
        int index) {
      return header_.get(index);
    }

    public static final int DATA_FIELD_NUMBER = 8;
    private java.util.List<Data> data_;
    /**
     * <code>repeated .Packet.Data data = 8;</code>
     */
    public java.util.List<Data> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .Packet.Data data = 8;</code>
     */
    public java.util.List<? extends DataOrBuilder>
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .Packet.Data data = 8;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .Packet.Data data = 8;</code>
     */
    public Data getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .Packet.Data data = 8;</code>
     */
    public DataOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }

    private void initFields() {
      header_ = java.util.Collections.emptyList();
      data_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getHeaderCount(); i++) {
        if (!getHeader(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < header_.size(); i++) {
        output.writeMessage(7, header_.get(i));
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(8, data_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < header_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, header_.get(i));
      }
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, data_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Packet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Packet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Packet)
        PacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PacketProto.internal_static_Packet_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PacketProto.internal_static_Packet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Packet.class, Builder.class);
      }

      // Construct using PacketProto.Packet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
          getDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          headerBuilder_.clear();
        }
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          dataBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PacketProto.internal_static_Packet_descriptor;
      }

      public Packet getDefaultInstanceForType() {
        return Packet.getDefaultInstance();
      }

      public Packet build() {
        Packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Packet buildPartial() {
        Packet result = new Packet(this);
        int from_bitField0_ = bitField0_;
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            header_ = java.util.Collections.unmodifiableList(header_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            data_ = java.util.Collections.unmodifiableList(data_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Packet) {
          return mergeFrom((Packet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Packet other) {
        if (other == Packet.getDefaultInstance()) return this;
        if (headerBuilder_ == null) {
          if (!other.header_.isEmpty()) {
            if (header_.isEmpty()) {
              header_ = other.header_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureHeaderIsMutable();
              header_.addAll(other.header_);
            }
            onChanged();
          }
        } else {
          if (!other.header_.isEmpty()) {
            if (headerBuilder_.isEmpty()) {
              headerBuilder_.dispose();
              headerBuilder_ = null;
              header_ = other.header_;
              bitField0_ = (bitField0_ & ~0x00000001);
              headerBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getHeaderFieldBuilder() : null;
            } else {
              headerBuilder_.addAllMessages(other.header_);
            }
          }
        }
        if (dataBuilder_ == null) {
          if (!other.data_.isEmpty()) {
            if (data_.isEmpty()) {
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureDataIsMutable();
              data_.addAll(other.data_);
            }
            onChanged();
          }
        } else {
          if (!other.data_.isEmpty()) {
            if (dataBuilder_.isEmpty()) {
              dataBuilder_.dispose();
              dataBuilder_ = null;
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000002);
              dataBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDataFieldBuilder() : null;
            } else {
              dataBuilder_.addAllMessages(other.data_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getHeaderCount(); i++) {
          if (!getHeader(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Packet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Packet) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Header> header_ =
        java.util.Collections.emptyList();
      private void ensureHeaderIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          header_ = new java.util.ArrayList<Header>(header_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Header, Header.Builder, HeaderOrBuilder> headerBuilder_;

      /**
       * <code>repeated .Packet.Header header = 7;</code>
       */
      public java.util.List<Header> getHeaderList() {
        if (headerBuilder_ == null) {
          return java.util.Collections.unmodifiableList(header_);
        } else {
          return headerBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Packet.Header header = 7;</code>
       */
      public int getHeaderCount() {
        if (headerBuilder_ == null) {
          return header_.size();
        } else {
          return headerBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Packet.Header header = 7;</code>
       */
      public Header getHeader(int index) {
        if (headerBuilder_ == null) {
          return header_.get(index);
        } else {
          return headerBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Packet.Header header = 7;</code>
       */
      public Builder setHeader(
          int index, Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeaderIsMutable();
          header_.set(index, value);
          onChanged();
        } else {
          headerBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Packet.Header header = 7;</code>
       */
      public Builder setHeader(
          int index, Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          ensureHeaderIsMutable();
          header_.set(index, builderForValue.build());
          onChanged();
        } else {
          headerBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Packet.Header header = 7;</code>
       */
      public Builder addHeader(Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeaderIsMutable();
          header_.add(value);
          onChanged();
        } else {
          headerBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Packet.Header header = 7;</code>
       */
      public Builder addHeader(
          int index, Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeaderIsMutable();
          header_.add(index, value);
          onChanged();
        } else {
          headerBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Packet.Header header = 7;</code>
       */
      public Builder addHeader(
          Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          ensureHeaderIsMutable();
          header_.add(builderForValue.build());
          onChanged();
        } else {
          headerBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Packet.Header header = 7;</code>
       */
      public Builder addHeader(
          int index, Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          ensureHeaderIsMutable();
          header_.add(index, builderForValue.build());
          onChanged();
        } else {
          headerBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Packet.Header header = 7;</code>
       */
      public Builder addAllHeader(
          Iterable<? extends Header> values) {
        if (headerBuilder_ == null) {
          ensureHeaderIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, header_);
          onChanged();
        } else {
          headerBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Packet.Header header = 7;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Packet.Header header = 7;</code>
       */
      public Builder removeHeader(int index) {
        if (headerBuilder_ == null) {
          ensureHeaderIsMutable();
          header_.remove(index);
          onChanged();
        } else {
          headerBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Packet.Header header = 7;</code>
       */
      public Header.Builder getHeaderBuilder(
          int index) {
        return getHeaderFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Packet.Header header = 7;</code>
       */
      public HeaderOrBuilder getHeaderOrBuilder(
          int index) {
        if (headerBuilder_ == null) {
          return header_.get(index);  } else {
          return headerBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Packet.Header header = 7;</code>
       */
      public java.util.List<? extends HeaderOrBuilder>
           getHeaderOrBuilderList() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(header_);
        }
      }
      /**
       * <code>repeated .Packet.Header header = 7;</code>
       */
      public Header.Builder addHeaderBuilder() {
        return getHeaderFieldBuilder().addBuilder(
            Header.getDefaultInstance());
      }
      /**
       * <code>repeated .Packet.Header header = 7;</code>
       */
      public Header.Builder addHeaderBuilder(
          int index) {
        return getHeaderFieldBuilder().addBuilder(
            index, Header.getDefaultInstance());
      }
      /**
       * <code>repeated .Packet.Header header = 7;</code>
       */
      public java.util.List<Header.Builder>
           getHeaderBuilderList() {
        return getHeaderFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Header, Header.Builder, HeaderOrBuilder>
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Header, Header.Builder, HeaderOrBuilder>(
                  header_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private java.util.List<Data> data_ =
        java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          data_ = new java.util.ArrayList<Data>(data_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Data, Data.Builder, DataOrBuilder> dataBuilder_;

      /**
       * <code>repeated .Packet.Data data = 8;</code>
       */
      public java.util.List<Data> getDataList() {
        if (dataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(data_);
        } else {
          return dataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Packet.Data data = 8;</code>
       */
      public int getDataCount() {
        if (dataBuilder_ == null) {
          return data_.size();
        } else {
          return dataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Packet.Data data = 8;</code>
       */
      public Data getData(int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);
        } else {
          return dataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Packet.Data data = 8;</code>
       */
      public Builder setData(
          int index, Data value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.set(index, value);
          onChanged();
        } else {
          dataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Packet.Data data = 8;</code>
       */
      public Builder setData(
          int index, Data.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Packet.Data data = 8;</code>
       */
      public Builder addData(Data value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(value);
          onChanged();
        } else {
          dataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Packet.Data data = 8;</code>
       */
      public Builder addData(
          int index, Data value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(index, value);
          onChanged();
        } else {
          dataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Packet.Data data = 8;</code>
       */
      public Builder addData(
          Data.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Packet.Data data = 8;</code>
       */
      public Builder addData(
          int index, Data.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Packet.Data data = 8;</code>
       */
      public Builder addAllData(
          Iterable<? extends Data> values) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, data_);
          onChanged();
        } else {
          dataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Packet.Data data = 8;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Packet.Data data = 8;</code>
       */
      public Builder removeData(int index) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.remove(index);
          onChanged();
        } else {
          dataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Packet.Data data = 8;</code>
       */
      public Data.Builder getDataBuilder(
          int index) {
        return getDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Packet.Data data = 8;</code>
       */
      public DataOrBuilder getDataOrBuilder(
          int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);  } else {
          return dataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Packet.Data data = 8;</code>
       */
      public java.util.List<? extends DataOrBuilder>
           getDataOrBuilderList() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data_);
        }
      }
      /**
       * <code>repeated .Packet.Data data = 8;</code>
       */
      public Data.Builder addDataBuilder() {
        return getDataFieldBuilder().addBuilder(
            Data.getDefaultInstance());
      }
      /**
       * <code>repeated .Packet.Data data = 8;</code>
       */
      public Data.Builder addDataBuilder(
          int index) {
        return getDataFieldBuilder().addBuilder(
            index, Data.getDefaultInstance());
      }
      /**
       * <code>repeated .Packet.Data data = 8;</code>
       */
      public java.util.List<Data.Builder>
           getDataBuilderList() {
        return getDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Data, Data.Builder, DataOrBuilder>
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Data, Data.Builder, DataOrBuilder>(
                  data_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Packet)
    }

    static {
      defaultInstance = new Packet(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Packet)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Packet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Packet_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Packet_Header_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Packet_Header_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Packet_Data_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Packet_Data_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021PacketProto.proto\"\302\001\n\006Packet\022\036\n\006header" +
      "\030\007 \003(\0132\016.Packet.Header\022\032\n\004data\030\010 \003(\0132\014.P" +
      "acket.Data\032I\n\006Header\022\014\n\004code\030\001 \002(\005\022\016\n\006in" +
      "tent\030\002 \001(\t\022\014\n\004data\030\003 \001(\t\022\023\n\013data_length\030" +
      "\004 \001(\005\0321\n\004Data\022\021\n\tjoinee_id\030\005 \001(\005\022\026\n\016uniq" +
      "ue_pckt_id\030\006 \001(\005B\rB\013PacketProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Packet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Packet_descriptor,
        new String[] { "Header", "Data", });
    internal_static_Packet_Header_descriptor =
      internal_static_Packet_descriptor.getNestedTypes().get(0);
    internal_static_Packet_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Packet_Header_descriptor,
        new String[] { "Code", "Intent", "Data", "DataLength", });
    internal_static_Packet_Data_descriptor =
      internal_static_Packet_descriptor.getNestedTypes().get(1);
    internal_static_Packet_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Packet_Data_descriptor,
        new String[] { "JoineeId", "UniquePcktId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
